(() => {
  "use strict";
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const bridge=window.chrome&&window.chrome.webview?window.chrome.webview:null;
  const ui={app:null,page:"tts",voiceFilter:"all",busy:false,dropped:null,dropDepth:0,setupSelected:new Set(),lastError:"",waveBuild:[0,0],waveContext:null};
  const send=(Action,Payload={})=>bridge&&bridge.postMessage({Action,Payload});
  const safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const lang=()=>ui.app&&ui.app.Settings?(ui.app.Settings.Language||"en"):"en";
  const t=(k,f)=>((window.VOXENA_I18N[lang()]||window.VOXENA_I18N.en||{})[k]||f||k);
  const l3=(en,ru,uk)=>lang()==="ru"?ru:((lang()==="uk"||lang()==="ua")?uk:en);
  function humanBytes(n){n=Number(n)||0;if(!n)return"—";const u=["B","KB","MB","GB","TB"];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++;}return `${n.toFixed(i>1?1:0)} ${u[i]}`;}
  function profileCopy(p){
    const maps={
      ru:{
        "cosyvoice3":{Description:"Очень естественный многоязычный синтез с сильным zero-shot клонированием и хорошей просодией.",Advantages:"Естественный ритм; высокая схожесть с диктором; сильное клонирование.",Disadvantages:"Крупная загрузка и тяжёлый рантайм; первый запуск дольше.",ReferenceRecommendation:"Рекомендуется 5–15 секунд чистой речи одного человека. Точная транскрипция обязательна; без музыки, эха и наложений.",RuntimeNote:"Нативный Windows-рантайм; извлечение speech-токенов может использовать CPU даже при синтезе на GPU."},
        "fish-s2-pro":{Description:"Флагманская 4B-модель с упором на реализм, эмоции и многоязычность.",Advantages:"Очень реалистичная речь; богатая эмоциональность; более 80 языков; свободные inline-теги.",Disadvantages:"Очень тяжёлая; для максимального качества рекомендуется около 24 ГБ VRAM. В Windows ускорение torch.compile отключено.",ReferenceRecommendation:"Оптимально 5–10 секунд чистой речи. Нужна точная транскрипция, минимум тишины и только один диктор.",RuntimeNote:"Windows-рантайм использует upstream Python inference с отключённым torch.compile."},
        "xtts-v2":{Description:"Проверенная многоязычная модель клонирования с небольшим размером и хорошей совместимостью.",Advantages:"Лёгкая; русский поддерживается; хороший клон даже с короткого референса.",Disadvantages:"Старая 24-кГц архитектура; по детализации и выразительности уступает новым флагманам.",ReferenceRecommendation:"6–20 секунд чистой речи. Транскрипция не требуется.",RuntimeNote:"Самый совместимый вариант для видеокарт с умеренным объёмом памяти."},
        "f5-tts-ru":{Description:"Flow-matching синтез с отдельным качественным русским чекпоинтом.",Advantages:"Хорошая естественность и схожесть при точной транскрипции; относительно компактная модель.",Disadvantages:"Сильно зависит от качества референса и текста; лицензия выбранного русского чекпоинта ограничивает коммерческое использование.",ReferenceRecommendation:"8–20 секунд чистой речи. Точная транскрипция обязательна — так не нужен дополнительный ASR и лучше выравнивание.",RuntimeNote:"Voxena заранее нормализует и сохраняет референс; F5 использует его непосредственно при каждом рендере."},
        "qwen3-tts":{Description:"Комплект из Base + CustomVoice 1.7B: качественное клонирование и девять встроенных голосов.",Advantages:"Очень сильное короткое клонирование; переиспользуемый voice prompt; русский; готовые голоса.",Disadvantages:"Для полного функционала скачиваются два чекпоинта, поэтому занимает больше места.",ReferenceRecommendation:"3–12 секунд чистой речи. Точная транскрипция обязательна: Voxena использует наиболее качественный ICL-режим.",RuntimeNote:"Voice-clone prompt рассчитывается один раз при создании голоса и сохраняется локально."},
        "chatterbox-v3":{Description:"Современная multilingual V3 модель с естественной разговорной подачей и хорошим сходством голоса.",Advantages:"Хороший русский; стабильное клонирование; сравнительно компактная; есть встроенный голос.",Disadvantages:"В аудио добавляется встроенный watermark; некоторым референсам нужна настройка выразительности.",ReferenceRecommendation:"Лучше 6–12 секунд чистой речи. Транскрипция не требуется; избегайте музыки и сильного комнатного эха.",RuntimeNote:"Voxena принудительно выбирает Multilingual V3. Speaker conditionals вычисляются один раз и сохраняются с голосом."}
      },
      uk:{
        "cosyvoice3":{Description:"Дуже природний багатомовний синтез із сильним zero-shot клонуванням і доброю просодією.",Advantages:"Природний ритм; висока схожість із диктором; сильне клонування.",Disadvantages:"Велике завантаження та важчий runtime; перше налаштування довше.",ReferenceRecommendation:"Рекомендовано 5–15 секунд чистого мовлення однієї людини. Точна транскрипція обов’язкова; без музики, відлуння та накладань.",RuntimeNote:"Нативний Windows-runtime; вилучення speech-токенів може використовувати CPU навіть під час синтезу на GPU."},
        "fish-s2-pro":{Description:"Флагманська 4B-модель з акцентом на реалізм, емоції та багатомовність.",Advantages:"Дуже реалістичне мовлення; багата емоційність; понад 80 мов; вільні inline-теги.",Disadvantages:"Дуже важка; для максимальної якості рекомендовано близько 24 ГБ VRAM. У Windows прискорення torch.compile вимкнено.",ReferenceRecommendation:"Оптимально 5–10 секунд чистого мовлення. Потрібна точна транскрипція, мінімум тиші та лише один диктор.",RuntimeNote:"Windows-runtime використовує upstream Python inference з вимкненим torch.compile."},
        "xtts-v2":{Description:"Перевірена багатомовна модель клонування з невеликим розміром і хорошою сумісністю.",Advantages:"Легка; російська підтримується; хороший клон навіть із короткого референсу.",Disadvantages:"Старіша 24-кГц архітектура; за деталізацією та виразністю поступається новим флагманам.",ReferenceRecommendation:"6–20 секунд чистого мовлення. Транскрипція не потрібна.",RuntimeNote:"Найсумісніший варіант для відеокарт із помірним обсягом пам’яті."},
        "f5-tts-ru":{Description:"Flow-matching синтез з окремим якісним російським чекпоінтом.",Advantages:"Хороша природність і схожість за точної транскрипції; відносно компактна модель.",Disadvantages:"Сильно залежить від якості референсу й тексту; ліцензія обраного російського чекпоінта обмежує комерційне використання.",ReferenceRecommendation:"8–20 секунд чистого мовлення. Точна транскрипція обов’язкова — це покращує вирівнювання.",RuntimeNote:"Voxena заздалегідь нормалізує та зберігає референс; F5 використовує його безпосередньо під час кожного рендера."},
        "qwen3-tts":{Description:"Комплект Base + CustomVoice 1.7B: якісне клонування та дев’ять вбудованих голосів.",Advantages:"Дуже сильне коротке клонування; багаторазовий voice prompt; російська; готові голоси.",Disadvantages:"Для повної функціональності завантажуються два чекпоінти, тому потрібно більше місця.",ReferenceRecommendation:"3–12 секунд чистого мовлення. Точна транскрипція обов’язкова: Voxena використовує найякісніший ICL-режим.",RuntimeNote:"Voice-clone prompt обчислюється один раз під час створення голосу та зберігається локально."},
        "chatterbox-v3":{Description:"Сучасна multilingual V3 модель із природною розмовною подачею та хорошою схожістю голосу.",Advantages:"Хороша російська; стабільне клонування; відносно компактна; є вбудований голос.",Disadvantages:"В аудіо додається вбудований watermark; деяким референсам потрібне налаштування виразності.",ReferenceRecommendation:"Найкраще 6–12 секунд чистого мовлення. Транскрипція не потрібна; уникайте музики й сильного кімнатного відлуння.",RuntimeNote:"Voxena примусово використовує Multilingual V3. Speaker conditionals обчислюються один раз і зберігаються разом із голосом."}
      }
    };
    const d=maps[lang()]||maps[(lang()==='ua')?'uk':'']||null;
    return d?Object.assign({},p,d[p.Id]||{}):p;
  }
  function applyI18n(){$$('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n,e.textContent));$$('[data-i18n-placeholder]').forEach(e=>e.placeholder=t(e.dataset.i18nPlaceholder,e.placeholder));document.documentElement.lang=lang();applyTagLabels();applyDynamicLabels();renderScriptHighlight();}

  function localizeStatusText(raw){
    let s=String(raw??'').replace(/^VOXENA:\s*/,'');
    if(lang()==='en')return s;
    let m;
    const exact={
      'Working…':l3('Working…','Выполняется…','Виконується…'),
      'Preparing…':l3('Preparing…','Подготовка…','Підготовка…'),
      'Preparing selected models…':l3('Preparing selected models…','Подготовка выбранных моделей…','Підготовка вибраних моделей…'),
      'Generating two voice variants…':l3('Generating two voice variants…','Генерация двух вариантов голоса…','Генерація двох варіантів голосу…'),
      'Analyzing and caching the new voice…':l3('Analyzing and caching the new voice…','Анализ и кэширование нового голоса…','Аналіз і кешування нового голосу…'),
      'Russian stress helper is ready':l3('Russian stress helper is ready','Помощник русских ударений готов','Помічник російських наголосів готовий'),
      'Model is ready.':l3('Model is ready.','Модель готова.','Модель готова.'),
      'Selected models are ready.':l3('Selected models are ready.','Выбранные модели готовы.','Вибрані моделі готові.'),
      'Operation cancelled. Downloads can resume later.':l3('Operation cancelled. Downloads can resume later.','Операция отменена. Загрузку можно продолжить позже.','Операцію скасовано. Завантаження можна продовжити пізніше.'),
      'Voice analyzed and cached locally.':l3('Voice analyzed and cached locally.','Голос проанализирован и сохранён в локальный кэш.','Голос проаналізовано та збережено в локальний кеш.'),
      'Voice import cancelled.':l3('Voice import cancelled.','Импорт голоса отменён.','Імпорт голосу скасовано.'),
      'Generation cancelled.':l3('Generation cancelled.','Генерация отменена.','Генерацію скасовано.'),
      'Another operation is already running.':l3('Another operation is already running.','Уже выполняется другая операция.','Уже виконується інша операція.'),
      'Model removed.':l3('Model removed.','Модель удалена.','Модель видалено.'),
      'Generate a short sentence to preview this built-in voice.':l3('Generate a short sentence to preview this built-in voice.','Сгенерируйте короткую фразу, чтобы прослушать этот встроенный голос.','Згенеруйте коротку фразу, щоб прослухати цей вбудований голос.')
    };
    if(exact[s])return exact[s];
    if((m=s.match(/^Rendering variant (\d+)\/(\d+) · seed (\d+)…$/)))return l3(s,`Рендер варианта ${m[1]}/${m[2]} · сид ${m[3]}…`,`Рендер варіанта ${m[1]}/${m[2]} · сід ${m[3]}…`);
    if((m=s.match(/^Downloading (.+)$/)))return l3(s,`Загрузка ${m[1]}`,`Завантаження ${m[1]}`);
    if((m=s.match(/^Compatibility check failed; repairing pinned dependencies for (.+)…$/)))return l3(s,`Проверка совместимости не пройдена; восстановление зависимостей для ${m[1]}…`,`Перевірку сумісності не пройдено; відновлення залежностей для ${m[1]}…`);
    if((m=s.match(/^(.+) runtime OK(.*)$/)))return l3(s,`Рантайм ${m[1]} готов${m[2]||''}`,`Рантайм ${m[1]} готовий${m[2]||''}`);
    if((m=s.match(/^(.+) files are ready$/)))return l3(s,`Файлы ${m[1]} готовы`,`Файли ${m[1]} готові`);
    if((m=s.match(/^Cached (.+)$/)))return l3(s,`Кэшировано: ${m[1]}`,`Закешовано: ${m[1]}`);
    return s;
  }
  function localizeStage(raw){let s=String(raw??'');if(lang()==='en')return s;if(s.startsWith('Runtime · '))return l3(s,'Рантайм · '+s.slice(10),'Рантайм · '+s.slice(10));if(s.startsWith('Source · '))return l3(s,'Исходники · '+s.slice(9),'Вихідний код · '+s.slice(9));return s;}

  function applyDynamicLabels(){
    const stress=$('#stressMarkBtn');if(stress)stress.title=l3('Mark stress on the selected vowel','Поставить ударение на выделенную гласную','Поставити наголос на виділену голосну');const qt=$('#quickTheme');if(qt)qt.title=l3('Theme','Тема','Тема');$$('.reveal-variant').forEach(b=>b.title=l3('Reveal file','Показать файл','Показати файл'));
    const d=$('#dropFeedbackText');if(d)d.textContent=l3('Release to attach','Отпустите, чтобы добавить','Відпустіть, щоб додати');
    const vt=$('#variantsTitle');if(vt)vt.textContent=l3('Two variants','Два варианта','Два варіанти');
    const vh=$('#variantsHint');if(vh)vh.textContent=l3('Same script · different seeds','Один текст · разные сиды','Один текст · різні сіди');
    [0,1].forEach(i=>{const title=$('#resultTitle'+i),meta=$('#resultMeta'+i);if(title&&!title.dataset.rendered)title.textContent=l3('Variant '+(i?'B':'A'),'Вариант '+(i?'B':'A'),'Варіант '+(i?'B':'A'));if(meta&&!meta.dataset.rendered)meta.textContent=l3('No render yet','Пока не сгенерировано','Ще не згенеровано');});
  }
  function applyTagLabels(){const d=(window.VOXENA_TAG_LABELS[lang()]||window.VOXENA_TAG_LABELS.en);$$('[data-tag]').forEach(b=>{const raw=b.dataset.tag,parts=raw.split(':');b.textContent=`[${d[parts[0]]||parts[0]}${parts[1]?':'+parts[1]:''}]`;});$$('[data-insert-tag]').forEach(b=>{const raw=b.dataset.insertTag,parts=raw.split(':');b.textContent=`[${d[parts[0]]||parts[0]}${parts[1]?':'+parts[1]:''}]`;});}
  function applyTheme(v){document.body.dataset.theme=(v||"dark")==="light"?"light":"dark";$$('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===document.body.dataset.theme));}
  function setPage(p){ui.page=p;$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+p));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));const n=$(`.nav[data-page="${p}"] b`);$('#titleContext').textContent=n?n.textContent:'Voxena';}
  function toast(kind,msg){const e=document.createElement('div');e.className='toast '+(kind||'info');e.textContent=msg;$('#toasts').appendChild(e);setTimeout(()=>e.remove(),4500);}
  function showError(m,d){ui.lastError=String(d||m||'Error');$('#errorText').textContent=ui.lastError;$('#errorModal').classList.remove('hidden');}
  async function copyError(){try{await navigator.clipboard.writeText(ui.lastError);$('#copyErrorBtn').textContent=l3('Copied!','Скопировано!','Скопійовано!');}catch{const a=document.createElement('textarea');a.value=ui.lastError;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();}}
  function setBusy(active,title){ui.busy=!!active;$('#busyOverlay').classList.toggle('hidden',!active);if(active){$('#busyTitle').textContent=localizeStatusText(title||'Working…');$('#busyFile').textContent=l3('Preparing…','Подготовка…','Підготовка…');$('#engineLine').textContent='';}else{$('#progressFill').style.width='0%';$('#progressPercent').textContent='0%';$('#progressSpeed').textContent='';$('#engineLine').textContent='';}}
  function updateProgress(p){if(!p)return;const pc=Math.max(0,Math.min(100,Number(p.Percent)||0));$('#progressFill').style.width=pc+'%';$('#progressPercent').textContent=pc.toFixed(pc<10?1:0)+'%';$('#progressSpeed').textContent=p.BytesPerSecond?humanBytes(p.BytesPerSecond)+'/s':'';$('#busyFile').textContent=[localizeStage(p.Stage),p.FileName].filter(Boolean).join(' · ');}

  const TAGRX=/\[(\/)?([\p{L}][\p{L}\p{Nd}_-]*)(?:\s*[:=]\s*([0-9]+(?:\.[0-9]+)?))?\]/gu;
  const aliases={happy:'happy',excited:'excited',sad:'sad',angry:'angry',calm:'calm',serious:'serious',sarcastic:'sarcastic',empathetic:'empathetic',whisper:'whisper',soft:'soft',loud:'loud',slow:'slow',fast:'fast',deep:'deep',bright:'bright',narration:'narration',pause:'pause',laughs:'laughs',sighs:'sighs',normal:'normal','радостно':'happy','восторженно':'excited','грустно':'sad','зло':'angry','спокойно':'calm','серьёзно':'serious','серьезно':'serious','саркастично':'sarcastic','сочувственно':'empathetic','шёпотом':'whisper','шепотом':'whisper','мягко':'soft','громко':'loud','медленно':'slow','быстро':'fast','глубже':'deep','ярко':'bright','диктор':'narration','пауза':'pause','смех':'laughs','вздох':'sighs','обычно':'normal','радісно':'happy','захоплено':'excited','сумно':'sad','сердито':'angry','спокійно':'calm','серйозно':'serious','співчутливо':'empathetic','пошепки':'whisper','лагідно':'soft','голосно':'loud','повільно':'slow','швидко':'fast','глибше':'deep','яскраво':'bright','сміх':'laughs','зітхання':'sighs','звичайно':'normal'};
  const tagClass=n=>{n=aliases[String(n).toLowerCase()]||String(n).toLowerCase();if(['happy'].includes(n))return'tag-blue';if(['excited','fast','laughs','bright'].includes(n))return'tag-cyan';if(['whisper','soft','deep','narration'].includes(n))return'tag-violet';if(['angry','loud','sarcastic'].includes(n))return'tag-rose';if(['sad','empathetic','sighs'].includes(n))return'tag-amber';if(['calm','serious','slow','normal'].includes(n))return'tag-slate';return'tag-neutral';};
  function highlightPlain(v){return safe(v).replace(/([\p{L}])́/gu,'<span class="manual-stress">$1́</span>');}
  function renderScriptHighlight(){const input=$('#scriptInput'),o=$('#scriptHighlight');if(!input||!o)return;let v=input.value||'',h='',last=0,m;TAGRX.lastIndex=0;while((m=TAGRX.exec(v))){h+=highlightPlain(v.slice(last,m.index));h+=`<span class="editor-tag ${tagClass(m[2])}">${safe(m[0])}</span>`;last=m.index+m[0].length;}h+=highlightPlain(v.slice(last));o.innerHTML=h||'<br>';syncEditorScroll();}
  function syncEditorScroll(){const i=$('#scriptInput'),o=$('#scriptHighlight');o.scrollTop=i.scrollTop;o.scrollLeft=i.scrollLeft;}
  function updateCounter(){const i=$('#scriptInput');$('#charCounter').textContent=`${i.value.length.toLocaleString()} / 25,000`;renderScriptHighlight();}
  function insertTag(tag){const i=$('#scriptInput'),s=i.selectionStart||0,e=i.selectionEnd||0,sel=i.value.slice(s,e),d=window.VOXENA_TAG_LABELS[lang()]||window.VOXENA_TAG_LABELS.en,parts=tag.split(':'),visible=(d[parts[0]]||parts[0])+(parts[1]?':'+parts[1]:''),simple=parts[0]==='pause'||['laughs','sighs','normal'].includes(parts[0]),rep=sel&&!simple?`[${visible}]${sel}[/${visible}]`:`[${visible}]`;i.setRangeText(rep,s,e,'end');i.focus();updateCounter();}
  function insertStress(){
    const i=$('#scriptInput');let s=i.selectionStart||0,e=i.selectionEnd||0,sel=i.value.slice(s,e);
    const vowels=/^[аеёиоуыэюяіїєАЕЁИОУЫЭЮЯІЇЄ]$/u;
    if(e-s!==1||!vowels.test(sel)){toast('info',l3('Select exactly one vowel first.','Сначала выделите ровно одну гласную.','Спочатку виділіть рівно одну голосну.'));i.focus();return;}
    let value=i.value;
    if(value.charAt(e)==='́'){i.setRangeText('',e,e+1,'end');i.focus();i.setSelectionRange(s,e);updateCounter();return;}
    const isWord=c=>!!c&&/[\p{L}\p{M}'’ʼ-]/u.test(c);
    let ws=s,we=e;while(ws>0&&isWord(value.charAt(ws-1)))ws--;while(we<value.length&&isWord(value.charAt(we)))we++;
    let before=value.slice(0,ws),word=value.slice(ws,we),after=value.slice(we);
    const local=s-ws;let clean='',cleanLocal=local;
    for(let n=0;n<word.length;n++){if(word.charAt(n)==='́'){if(n<local)cleanLocal--;continue;}clean+=word.charAt(n);}
    value=before+clean+after;i.value=value;s=ws+cleanLocal;e=s+1;
    i.setRangeText('́',e,e,'end');i.focus();i.setSelectionRange(s,e);updateCounter();
  }

  function updateSliders(){$('#stabilityValue').textContent=$('#stabilitySlider').value+'%';$('#speedValue').textContent=(Number($('#speedSlider').value)/100).toFixed(2)+'×';const p=Number($('#pitchSlider').value);$('#pitchValue').textContent=(p>0?'+':'')+p+' st';}
  function syncSettingsFromControls(){if(!ui.app)return;const s=ui.app.Settings;s.SelectedVoiceId=$('#voiceSelect').value;s.Stability=Number($('#stabilitySlider').value)/100;s.Speed=Number($('#speedSlider').value)/100;s.Pitch=Number($('#pitchSlider').value);s.OutputFormat=$('#formatSelect').value;s.Normalize=$('#normalizeToggle').checked;s.TrimSilence=$('#trimToggle').checked;send('saveSettings',{settings:s});}
  function syncSettingsPage(){if(!ui.app)return;const s=ui.app.Settings;$('#settingsLanguage').value=s.Language||'en';$('#quickLanguage').value=s.Language||'en';$('#autoPlayToggle').checked=!!s.AutoPlay;$('#openAfterToggle').checked=!!s.OpenOutputAfterGeneration;$('#sampleRateSelect').value=String(s.SampleRate||44100);$('#bitrateSelect').value=String(s.BitrateKbps||192);$('#stressToggle').checked=s.StressRussian!==false;$('#deviceInput').value=s.DevicePreference||'auto';$('#devToolsToggle').checked=!!s.EnableDevTools;$('#outputPath').textContent=s.OutputFolder||'';applyTheme(s.Theme);}
  function collectSettings(){if(!ui.app)return;const s=ui.app.Settings;s.Language=$('#settingsLanguage').value;s.AutoPlay=$('#autoPlayToggle').checked;s.OpenOutputAfterGeneration=$('#openAfterToggle').checked;s.SampleRate=Number($('#sampleRateSelect').value)||44100;s.BitrateKbps=Number($('#bitrateSelect').value)||192;s.StressRussian=$('#stressToggle').checked;s.DevicePreference=($('#deviceInput').value||'auto').trim();s.EnableDevTools=$('#devToolsToggle').checked;$('#quickLanguage').value=s.Language;applyI18n();send('saveSettings',{settings:s});}

  function renderModels(){if(!ui.app)return;const h=ui.app.Hardware||{};$('#gpuName').textContent=h.GpuName||'—';$('#gpuVram').textContent=h.VramMb?`${(h.VramMb/1024).toFixed(1)} GB`:'—';$('#ramSize').textContent=h.RamMb?`${(h.RamMb/1024).toFixed(0)} GB`:'—';$('#stressState').textContent=ui.app.StressModelReady?l3('Ready','Готов','Готово'):l3('Prepared automatically','Подготовится автоматически','Підготується автоматично');$('#installedModelCount').textContent=(ui.app.Profiles||[]).filter(p=>p.Installed).length;
    $('#modelGrid').innerHTML=(ui.app.Profiles||[]).map(raw=>{const p=profileCopy(raw),state=p.Installed?l3('Installed','Установлена','Встановлена'):l3('Not installed','Не установлена','Не встановлена');return `<div class="panel model-card ${p.Recommended?'recommended':''}"><div class="model-head"><div><h3>${safe(p.Name)}</h3><small>${safe(p.VersionName)}</small></div><span class="model-state ${p.Installed?'installed':''}">${state}</span></div><p>${safe(p.Description)}</p><div class="model-tags"><span>${safe(p.DiskSize)}</span><span>${safe(p.Vram)}</span><span>${safe(p.License)}</span><span>${safe(p.Languages)}</span>${p.Recommended?`<span>${l3('VRAM fit','Подходит по VRAM','Підходить за VRAM')}</span>`:''}</div><div class="proscons"><div class="pros"><b>${l3('Pros','Плюсы','Переваги')}</b>${safe(p.Advantages)}</div><div class="cons"><b>${l3('Cons','Минусы','Недоліки')}</b>${safe(p.Disadvantages)}</div></div><div class="model-note">${safe(p.RuntimeNote||'')}</div><div class="model-actions"><button class="btn ghost upstream" data-url="${safe(p.UpstreamUrl)}">${l3('Upstream','Проект','Проєкт')}</button>${p.Installed?`<button class="btn danger remove-model" data-id="${safe(p.Id)}">${l3('Remove','Удалить','Видалити')}</button>`:`<button class="btn primary install-model" data-id="${safe(p.Id)}">${l3('Install','Скачать','Завантажити')}</button>`}</div></div>`}).join('');
    $$('.install-model').forEach(b=>b.onclick=()=>send('installModel',{id:b.dataset.id}));$$('.remove-model').forEach(b=>b.onclick=()=>send('removeModel',{id:b.dataset.id}));$$('.upstream').forEach(b=>b.onclick=()=>send('openExternal',{url:b.dataset.url}));renderSetupModels();
  }
  function renderSetupModels(){if(!ui.app)return;const host=$('#setupModels');host.innerHTML=(ui.app.Profiles||[]).map(raw=>{const p=profileCopy(raw),sel=ui.setupSelected.has(p.Id);return `<label class="setup-model ${sel?'selected':''}" data-id="${safe(p.Id)}"><input type="checkbox" ${sel?'checked':''}><h3>${safe(p.Name)} ${p.Recommended?`· ${l3('recommended','рекомендуется','рекомендовано')}`:''}</h3><div class="size">${safe(p.DiskSize)} · ${safe(p.Vram)}</div><p>${safe(p.Description)}</p><div class="pc"><span>+ ${safe(p.Advantages)}</span><span>− ${safe(p.Disadvantages)}</span></div></label>`}).join('');$$('.setup-model',host).forEach(card=>{card.onclick=e=>{if(e.target.tagName!=='INPUT')e.preventDefault();const id=card.dataset.id;if(ui.setupSelected.has(id))ui.setupSelected.delete(id);else ui.setupSelected.add(id);renderSetupModels();};});const ps=(ui.app.Profiles||[]).filter(p=>ui.setupSelected.has(p.Id));const total=ps.reduce((a,p)=>a+(Number(p.ApproxBytes)||0),0);$('#setupSelectionCount').textContent=l3(`${ps.length} models`,`${ps.length} моделей`,`${ps.length} моделей`);$('#setupSelectionSize').textContent='~'+(total/1e9).toFixed(1)+l3(' GB + runtime + ~0.2 GB Gemma 4 stress helper',' ГБ + рантайм + ~0.2 ГБ Gemma 4 для ударений',' ГБ + рантайм + ~0.2 ГБ Gemma 4 для наголосів');$('#setupInstallBtn').disabled=!ps.length;}

  function renderVoices(){
    if(!ui.app)return;
    const voices=ui.app.Voices||[],filter=ui.voiceFilter,shown=voices.filter(v=>filter==='all'||v.Kind===filter);
    $('#voiceGrid').innerHTML=shown.length?shown.map(v=>`<div class="panel voice-card ${v.Available===false?'unavailable':''}"><div class="voice-head"><div class="voice-avatar">♪</div><div><h3>${safe(v.Name)}</h3><div class="voice-model">(${safe(v.ModelName||v.ModelId)})</div></div></div><p>${safe(v.Description||'')}</p><div class="voice-meta"><span>${v.Kind==='custom'?l3('Cloned','Клонированный','Клонований'):l3('Built-in','Встроенный','Вбудований')}</span><span>${v.Available===false?l3('model missing','модель удалена','модель видалена'):(v.Prepared?l3('ready','готов','готовий'):'…')}</span></div><div class="voice-actions"><button class="btn ghost use-voice" data-id="${safe(v.Id)}" ${v.Available===false?'disabled':''}>${l3('Use','Использовать','Використати')}</button>${v.Kind==='custom'?`<button class="btn danger delete-voice" data-id="${safe(v.Id)}" title="${l3('Delete only this cloned voice','Удалить только этот клонированный голос','Видалити лише цей клонований голос')}">✕ ${l3('Delete','Удалить','Видалити')}</button>`:''}</div></div>`).join(''):`<div class="panel info-strip"><span>i</span><div><b>${l3('No voices yet','Голосов пока нет','Голосів поки немає')}</b><p>${l3('Install a model and clone a voice. Qwen3-TTS and Chatterbox also provide built-in voices.','Установите модель и клонируйте голос. Qwen3-TTS и Chatterbox также добавят встроенные голоса.','Встановіть модель і клонуйте голос. Qwen3-TTS та Chatterbox також додадуть вбудовані голоси.')}</p></div></div>`;
    $$('.use-voice').forEach(b=>b.onclick=()=>{$('#voiceSelect').value=b.dataset.id;ui.app.Settings.SelectedVoiceId=b.dataset.id;setPage('tts');send('saveSettings',{settings:ui.app.Settings});});
    $$('.delete-voice').forEach(b=>b.onclick=()=>send('deleteVoice',{id:b.dataset.id}));
    renderVoiceSelect();
  }
  function renderVoiceSelect(){const select=$('#voiceSelect'),voices=(ui.app&&ui.app.Voices||[]).filter(v=>v.Available!==false);select.innerHTML=voices.length?voices.map(v=>`<option value="${safe(v.Id)}">${safe(v.Name)} (${safe(v.ModelName||v.ModelId)})</option>`).join(''):`<option value="">${l3('No available voices','Нет доступных голосов','Немає доступних голосів')}</option>`;const desired=ui.app&&ui.app.Settings.SelectedVoiceId;if(desired&&voices.some(v=>v.Id===desired))select.value=desired;else if(voices.length)select.value=voices[0].Id;}

  function openClone(){if(!ui.app)return;const models=(ui.app.Profiles||[]).filter(p=>p.Installed);if(!models.length){toast('info',l3('Install at least one model first.','Сначала установите хотя бы одну модель.','Спочатку встановіть хоча б одну модель.'));setPage('models');return;}$('#cloneModel').innerHTML=models.map(p=>`<option value="${safe(p.Id)}">${safe(p.Name)}</option>`).join('');ui.dropped=null;$('#dropFileName').textContent='';$('#createDroppedVoiceBtn').disabled=true;$('#cloneName').value='';$('#cloneDescription').value='';$('#cloneTranscript').value='';updateCloneRequirements();$('#cloneModal').classList.remove('hidden');}
  function updateCloneRequirements(){if(!ui.app)return;const raw=(ui.app.Profiles||[]).find(p=>p.Id===$('#cloneModel').value);if(!raw)return;const p=profileCopy(raw),required=!!p.CloneTranscriptRequired;$('#cloneRecommendation').innerHTML=`<b>${safe(p.Name)} · ${safe(p.VersionName)}</b><br>${safe(p.ReferenceRecommendation)}<br><span>${safe(p.DiskSize)} · ${safe(p.License)}</span>`;$('#transcriptField').classList.toggle('hidden',!required);$('#transcriptHint').textContent=required?l3('Required. It must exactly match the spoken reference.','Обязательно. Текст должен точно совпадать с тем, что произносится в референсе.','Обов’язково. Текст має точно збігатися з тим, що вимовляється у референсі.'):'';$('#cloneTranscript').required=required;if(!required)$('#cloneTranscript').value='';}
  function validAudio(f){return f&&['wav','mp3','flac','ogg','m4a','aac','opus'].includes((f.name.split('.').pop()||'').toLowerCase());}
  function acceptDrop(f){if(!validAudio(f)){toast('error',l3('Unsupported audio file.','Неподдерживаемый аудиофайл.','Непідтримуваний аудіофайл.'));return;}if(f.size>48*1024*1024){toast('info',l3('Use Browse for files over 48 MB.','Для файлов больше 48 МБ используйте кнопку «Выбрать».','Для файлів понад 48 МБ використовуйте кнопку «Вибрати».'));return;}ui.dropped=f;$('#dropFileName').textContent=`${f.name} · ${humanBytes(f.size)}`;if(!$('#cloneName').value.trim())$('#cloneName').value=f.name.replace(/\.[^.]+$/,'');$('#createDroppedVoiceBtn').disabled=false;}
  function clonePayload(){const p=(ui.app.Profiles||[]).find(x=>x.Id===$('#cloneModel').value);const tr=$('#cloneTranscript').value.trim();if(p&&p.CloneTranscriptRequired&&!tr){toast('info',l3('This model requires an exact transcript.','Для этой модели нужна точная транскрипция.','Для цієї моделі потрібна точна транскрипція.'));return null;}return {modelId:$('#cloneModel').value,name:$('#cloneName').value,description:$('#cloneDescription').value,transcript:tr};}
  function importDropped(){if(!ui.dropped)return;const base=clonePayload();if(!base)return;const f=ui.dropped,r=new FileReader();r.onload=()=>{send('importAudioData',Object.assign(base,{data:r.result,fileName:f.name}));};r.onerror=()=>toast('error','Could not read audio.');r.readAsDataURL(f);}

  const defaultWave=()=>[.2,.36,.58,.3,.48,.8,.62,.27,.42,.72,.51,.25,.6,.86,.45,.3,.54,.7,.35,.2,.49,.76,.9,.56,.28,.44,.69,.39,.22,.53,.82,.64,.31,.47,.73,.42,.24,.58,.88,.61,.36,.5,.77,.33,.2,.45,.68,.52];
  function renderWave(index,h){const host=$('#waveformBars'+index);if(!host)return;host.innerHTML=(h&&h.length?h:defaultWave()).map(v=>`<i class="wave-bar" style="--bar:${Math.max(.08,Math.min(1,v))}"></i>`).join('');updatePlayer(index);}
  async function buildWave(index,url){const id=++ui.waveBuild[index];renderWave(index,defaultWave());if(!url)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;if(!ui.waveContext)ui.waveContext=new C();const ab=await (await fetch(url,{cache:'no-store'})).arrayBuffer(),buf=await ui.waveContext.decodeAudioData(ab.slice(0));if(id!==ui.waveBuild[index])return;const count=44,block=Math.max(1,Math.floor(buf.length/count)),chs=Array.from({length:buf.numberOfChannels},(_,i)=>buf.getChannelData(i)),raw=[];for(let i=0;i<count;i++){let peak=0,e=0,n=0,st=i*block,en=Math.min(buf.length,st+block),step=Math.max(1,Math.floor((en-st)/100));for(let j=st;j<en;j+=step){let sm=0;for(const c of chs)sm+=Math.abs(c[j]||0);sm/=chs.length;peak=Math.max(peak,sm);e+=sm*sm;n++;}raw.push(Math.max(peak*.68,Math.sqrt(e/Math.max(1,n))*1.35));}const mx=Math.max(.001,...raw),h=raw.map((v,i)=>{const a=raw[Math.max(0,i-1)],c=raw[Math.min(raw.length-1,i+1)],sm=a*.22+v*.56+c*.22,z=sm/mx;return Math.max(.14,.14+Math.pow(z,.62)*.86);});renderWave(index,h);}catch{renderWave(index,defaultWave());}}
  const fmtTime=v=>{v=Math.max(0,Math.floor(Number(v)||0));return `${Math.floor(v/60)}:${String(v%60).padStart(2,'0')}`;};
  function updatePlayer(index){const a=$('#audioPlayer'+index),bars=$$('#waveformBars'+index+' .wave-bar');if(!a)return;const d=Number.isFinite(a.duration)?a.duration:0,r=d?Math.max(0,Math.min(1,a.currentTime/d)):0;bars.forEach((b,i)=>b.classList.toggle('played',i<Math.round(r*bars.length)));const track=$('#waveformTrack'+index),ph=$('#waveformPlayhead'+index);if(track&&ph)ph.style.left=(10+Math.max(0,track.clientWidth-20)*r)+'px';$('#audioCurrentTime'+index).textContent=fmtTime(a.currentTime);$('#audioDuration'+index).textContent=fmtTime(d);$('#audioPlayBtn'+index).textContent=a.paused?'▶':'❚❚';}
  function showVariant(index,r){const title=$('#resultTitle'+index),meta=$('#resultMeta'+index),a=$('#audioPlayer'+index);title.dataset.rendered='1';meta.dataset.rendered='1';title.textContent=l3('Variant '+(index?'B':'A'),'Вариант '+(index?'B':'A'),'Варіант '+(index?'B':'A'));meta.textContent=`${r.ModelId||''} · Seed ${r.Seed||0}`;a.pause();a.src=r.AudioUrl||'';a.load();buildWave(index,r.AudioUrl||'');if(index===0&&ui.app.Settings.AutoPlay)a.play().catch(()=>{});}
  function resetGenerations(){[0,1].forEach(index=>{const title=$('#resultTitle'+index),meta=$('#resultMeta'+index),a=$('#audioPlayer'+index);if(a){a.pause();a.removeAttribute('src');a.load();}if(title){delete title.dataset.rendered;title.textContent=l3('Variant '+(index?'B':'A'),'Вариант '+(index?'B':'A'),'Варіант '+(index?'B':'A'));}if(meta){delete meta.dataset.rendered;meta.textContent=l3('Generating…','Генерация…','Генерація…');}renderWave(index,defaultWave());});}
  function showGenerations(payload){const rs=(payload&&payload.results)||[];rs.slice(0,2).forEach((r,i)=>showVariant(i,r));}

  function renderAll(){if(!ui.app)return;applyI18n();applyTheme(ui.app.Settings.Theme);syncSettingsPage();renderModels();renderVoices();$('#aboutVersion').textContent=ui.app.Version||'';$('#stabilitySlider').value=Math.round((ui.app.Settings.Stability??.55)*100);$('#speedSlider').value=Math.round((ui.app.Settings.Speed??1)*100);$('#pitchSlider').value=ui.app.Settings.Pitch??0;$('#formatSelect').value=ui.app.Settings.OutputFormat||'mp3';$('#normalizeToggle').checked=ui.app.Settings.Normalize!==false;$('#trimToggle').checked=ui.app.Settings.TrimSilence!==false;updateSliders();const installed=(ui.app.Profiles||[]).filter(p=>p.Installed).length;$('#setupModal').classList.toggle('hidden',!!ui.app.Settings.FirstRunCompleted);}
  function handle(e){const m=e.data||{},d=m.data||{};switch(m.type){case'state':ui.app=d.app;renderAll();break;case'windowState':document.body.classList.toggle('maximized',!!d.maximized);break;case'busy':setBusy(!!d.active,d.text);break;case'downloadProgress':updateProgress(d);break;case'engineLine':$('#engineLine').textContent=localizeStatusText(d.text||'');break;case'toast':toast(d.kind,localizeStatusText(d.message));break;case'error':setBusy(false);showError(d.message,d.detail);break;case'voiceImported':$('#cloneModal').classList.add('hidden');break;case'voicePreview':if(d.url)new Audio(d.url).play().catch(()=>{});break;case'generationReset':resetGenerations();break;case'generationComplete':showGenerations(d);break;}}

  function bind(){
    $$('.nav').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$$('[data-window]').forEach(b=>b.onclick=e=>{e.stopPropagation();send('titlebar',{command:b.dataset.window});});$('#titlebarDrag').onmousedown=e=>e.button===0&&send('titlebar',{command:'drag'});$('#titlebarDrag').ondblclick=()=>send('titlebar',{command:'togglemaximize'});$('#busyDragHandle').onmousedown=e=>e.button===0&&send('titlebar',{command:'drag'});$('#setupModal .setup-brand').onmousedown=e=>{if(e.button===0&&!e.target.closest('button,input,select,textarea,a'))send('titlebar',{command:'drag'});};
    $('#quickTheme').onclick=()=>{if(!ui.app)return;ui.app.Settings.Theme=document.body.dataset.theme==='light'?'dark':'light';applyTheme(ui.app.Settings.Theme);send('saveSettings',{settings:ui.app.Settings});};$('#quickLanguage').onchange=e=>{if(!ui.app)return;ui.app.Settings.Language=e.target.value;$('#settingsLanguage').value=e.target.value;applyI18n();renderAll();send('saveSettings',{settings:ui.app.Settings});};
    const si=$('#scriptInput');si.spellcheck=false;si.setAttribute('spellcheck','false');si.setAttribute('autocorrect','off');si.setAttribute('autocapitalize','off');$$('input[type=text],input:not([type]),textarea').forEach(x=>{x.spellcheck=false;x.setAttribute('spellcheck','false');});si.oninput=updateCounter;si.onscroll=syncEditorScroll;$$('[data-tag]').forEach(b=>b.onclick=()=>insertTag(b.dataset.tag));$$('[data-insert-tag]').forEach(b=>b.onclick=()=>{insertTag(b.dataset.insertTag);$('#tagsModal').classList.add('hidden');});$('#stressMarkBtn').onmousedown=e=>e.preventDefault();$('#stressMarkBtn').onclick=insertStress;$('#moreTagsBtn').onclick=()=>$('#tagsModal').classList.remove('hidden');
    $('#cloneVoiceBtn').onclick=openClone;$('#cloneInlineBtn').onclick=openClone;$('#cloneModel').onchange=updateCloneRequirements;$('#browseCloneBtn').onclick=()=>{const p=clonePayload();if(p)send('browseVoice',p);};$('#createDroppedVoiceBtn').onclick=importDropped;const drop=$('#cloneDropZone');drop.addEventListener('dragenter',e=>{e.preventDefault();ui.dropDepth++;drop.classList.add('dragging');});drop.addEventListener('dragover',e=>{e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect='copy';drop.classList.add('dragging');});drop.addEventListener('dragleave',e=>{e.preventDefault();ui.dropDepth=Math.max(0,ui.dropDepth-1);if(!ui.dropDepth)drop.classList.remove('dragging');});drop.addEventListener('drop',e=>{e.preventDefault();ui.dropDepth=0;drop.classList.remove('dragging');acceptDrop(e.dataTransfer.files[0]);});drop.onclick=()=>{const p=clonePayload();if(p)send('browseVoice',p);};
    $$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$$('[data-voice-filter]').forEach(b=>b.onclick=()=>{ui.voiceFilter=b.dataset.voiceFilter;$$('[data-voice-filter]').forEach(x=>x.classList.toggle('active',x===b));renderVoices();});
    $('#setupInstallBtn').onclick=()=>send('installModels',{ids:Array.from(ui.setupSelected)});$('#setupSkipBtn').onclick=()=>send('skipFirstSetup');$('#cancelBusyBtn').onclick=()=>send('cancelOperation');$('#copyErrorBtn').onclick=copyError;
    $('#generateBtn').onclick=()=>{if(!ui.app)return;const text=si.value;if(!text.trim())return toast('info',l3('Enter some text.','Введите текст.','Введіть текст.'));if(!$('#voiceSelect').value)return toast('info',l3('No voice is available.','Нет доступного голоса.','Немає доступного голосу.'));syncSettingsFromControls();send('generate',{text,voiceId:$('#voiceSelect').value,stability:Number($('#stabilitySlider').value)/100,speed:Number($('#speedSlider').value)/100,pitch:Number($('#pitchSlider').value),expressiveness:ui.app.Settings.Expressiveness??.5,format:$('#formatSelect').value,sampleRate:ui.app.Settings.SampleRate||44100,bitrateKbps:ui.app.Settings.BitrateKbps||192,normalize:$('#normalizeToggle').checked,trimSilence:$('#trimToggle').checked,seed:Number($('#seedInput').value)||0});};
    $('#resetVoiceSettings').onclick=()=>{$('#stabilitySlider').value=55;$('#speedSlider').value=100;$('#pitchSlider').value=0;updateSliders();};['stabilitySlider','speedSlider','pitchSlider'].forEach(id=>$('#'+id).oninput=updateSliders);['stabilitySlider','speedSlider','pitchSlider','formatSelect','normalizeToggle','trimToggle','voiceSelect'].forEach(id=>$('#'+id).onchange=syncSettingsFromControls);
    [0,1].forEach(index=>{const a=$('#audioPlayer'+index);$('#audioPlayBtn'+index).onclick=()=>{if(!a.src)return;[0,1].filter(x=>x!==index).forEach(x=>{const other=$('#audioPlayer'+x);if(other&&!other.paused)other.pause();});a.paused?a.play().catch(()=>{}):a.pause();};$('#waveformTrack'+index).onclick=e=>{if(!Number.isFinite(a.duration)||!a.duration)return;const r=e.currentTarget.getBoundingClientRect();a.currentTime=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*a.duration;updatePlayer(index);};['loadedmetadata','timeupdate','play','pause','ended','durationchange'].forEach(ev=>a.addEventListener(ev,()=>updatePlayer(index)));});
    $('#openOutputBtn').onclick=()=>send('openOutput');$('#browseOutputBtn').onclick=()=>send('pickOutputFolder');$$('.reveal-variant').forEach(b=>b.onclick=()=>send('revealGenerated',{index:Number(b.dataset.index)||0}));$$('.save-variant').forEach(b=>b.onclick=()=>send('saveGeneratedAs',{index:Number(b.dataset.index)||0}));$('#manageModelsBtn').onclick=()=>setPage('models');
    ['settingsLanguage','autoPlayToggle','openAfterToggle','sampleRateSelect','bitrateSelect','stressToggle','devToolsToggle'].forEach(id=>$('#'+id).onchange=collectSettings);$('#deviceInput').onblur=collectSettings;$$('[data-theme-choice]').forEach(b=>b.onclick=()=>{if(!ui.app)return;ui.app.Settings.Theme=b.dataset.themeChoice;applyTheme(ui.app.Settings.Theme);send('saveSettings',{settings:ui.app.Settings});});
  }
  document.addEventListener('DOMContentLoaded',()=>{bind();renderWave(0,defaultWave());renderWave(1,defaultWave());updateCounter();updateSliders();if(bridge){bridge.addEventListener('message',handle);send('appReady');}else showError('WebView bridge unavailable.');});
})();
